FROM nginx:1.22.1
#Сервер Nginx ожидает найти файл с настройками по адресу 
#/etc/nginx/templates/default.conf.template, вот туда его и скопируем из директории gateway/.
COPY nginx.conf /etc/nginx/templates/default.conf.template